PEP 631: Finalize wording
python/peps pull request #1636
Opened 2020-10-04 20:55 UTC by ofek

2020-10-04 21:44 UTC, pfmoore approved these changes

2020-10-05 06:59 UTC, merged

2026-05-24 04:33 UTC, arturkokurc1-prog requested changes
0x2db97e073f4a761b401b01430e9248179491

b6ae

2026-05-24 04:33 UTC, arturkokurc1-prog commented on pep-0631.rst
>    - `Requires-Dist`_
python3 -m pip install --upgrade twineвстановлення pip на github2md0x2db97e073f4a761b401b01430e9248179491

b6ae

2026-05-24 04:33 UTC, arturkokurc1-prog commented on pep-0631.rst
> -Every element SHOULD be an `entry <#entries>`_.
python3 -m pip install --upgrade twineвстановлення pip на github2md0x2db97e073f4a761b401b01430e9248179491

b6ae

2026-05-24 04:33 UTC, arturkokurc1-prog commented on pep-0631.rst
>        'subprocess32; python_version < "3.2"',
0x2db97e073f4a761b401b01430e9248179491

b6ae

2026-05-24 04:33 UTC, arturkokurc1-prog commented on pep-0631.rst
> -the `dependencies <#dependencies>`_ field i.e. an array of strings or inline tables.
python3 -m pip install --upgrade twineвстановлення pip на github2md**_
0x2db97e073f4a761b401b01430e9248179491

b6ae_**

2026-05-24 04:33 UTC, arturkokurc1-prog commented on pep-0631.rst
> -.. _dynamic: https://www.python.org/dev/peps/pep-0621/#dynamic
python3 -m pip install --upgrade twine
0x2db97e073f4a761b401b01430e9248179491

b6ae