PEP 9999: Editable installs for PEP-517 style build backends
python/peps pull request #1944
Opened 2021-05-02 10:41 UTC by sbidoul

2021-05-02 10:41 UTC, the-knights-who-say-ni commented
Hello, and thanks for your contribution!

I'm a bot set up to make sure that the project can legally accept this contribution by verifying everyone involved has signed the [PSF contributor agreement](https://www.python.org/psf/contrib/contrib-form/) (CLA).



## CLA Missing

Our records indicate the following people have not signed the CLA:

@dholth

For legal reasons we need all the people listed to sign the CLA before we can look at your contribution. Please follow [the steps outlined in the CPython devguide](https://devguide.python.org/pullrequest/#licensing) to rectify this issue.

If you have recently signed the CLA, please wait at least one business day
before our records are updated.


You can [check yourself](https://check-python-cla.herokuapp.com/) to see if the CLA has been received.

Thanks again for the contribution, we look forward to reviewing it!

2021-05-02 10:45 UTC, sbidoul commented
GitHub apparently brought over the discussion we had in https://github.com/sbidoul/peps/pull/1. I assume this is not an issue.

@pfmoore as sponsor will you assign a PEP number ?
@dholth as the first commit is yours it looks like you need to sign the CLA. Or maybe not if commits are squashed before merging.

2021-05-02 13:04 UTC, pfmoore commented
I'll wait for the CLA from @dholth just to be on the safe side (although I'm surprised he hasn't already signed it, as he was the author of the wheel PEP).

2021-05-02 13:09 UTC, sbidoul commented
The CLA issue is suprising indeed because there are several other commits from Daniel with the exact same e-mail address.

I add to change his email in the document itself because the CI complained that *some authors have more than one email address listed:    Daniel Holth: ['dholth@gmail.com', 'dholth@fastmail.fm']*

I tentatively used number 667 to get a green build.

2021-05-02 14:25 UTC, domdfcoding commented on pep-0667.rst
> +This PEP adds a single optional hook to the PEP-517 backend interface. The hook
Other than here and in the title you've written PEP 517 (i.e. without the hyphen)

2021-05-02 14:25 UTC, domdfcoding commented on pep-0667.rst
> +backend implement this specification, some minor differences may be visible
```suggestion
behave identically as a regular installation. Depending on the way build
backends implement this specification, some minor differences may be visible
```

2021-05-02 16:06 UTC, Rosuav commented
PEP number 657 looks to be available; you should be able to grab that. In the (unlikely) event that someone else grabs that number, you'll get a merge conflict, and can bump it to 658.

2021-05-02 17:13 UTC, pradyunsg commented
And the title too! :P

2021-05-03 22:46 UTC, brettcannon requested changes
Please add Paul in `.github/CODEOWNERS` for this file as the PEP sponsor.

2021-05-03 22:50 UTC, brettcannon commented
We also need the CLA to be signed.

2021-05-04 07:09 UTC, pradyunsg commented on pep-0657.rst
> +Discussions-To: https://discuss.python.org/t/draft-pep-editable-installs-for-pep-517-style-build-backends/8510
```suggestion
Discussions-To: https://discuss.python.org/t/8510
```

A cleaner URL.

2021-05-04 20:48 UTC, pfmoore requested changes
This needs @dholth to sign the CLA but otherwise it looks OK to me.

2021-05-05 20:30 UTC, pfmoore commented
@brettcannon All we're waiting on is the CLA. I don't know whether we're allowed to ignore the CLA requirement and merge this, but other than that, I've approved this...

2021-05-05 21:34 UTC, dholth commented
I'll get it taken care of.

On Wed, May 5, 2021, at 4:30 PM, Paul Moore wrote:
> 

> @brettcannon <https://github.com/brettcannon> All we're waiting on is the CLA. I don't know whether we're allowed to ignore the CLA requirement and merge this, but other than that, I've approved this...


> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/python/peps/pull/1944#issuecomment-832986291>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AABSZEVPSU3FIGSXW27CIG3TMGTGFANCNFSM437IVTMA>.

2021-05-08 17:42 UTC, pradyunsg commented
Given #1950, this likely needs renumbering.

2021-05-08 18:19 UTC, pfmoore requested changes
PR title and filename will also need changing to reflect the new PEP number.

2021-05-08 18:19 UTC, pfmoore commented on .github/CODEOWNERS
> +pep-0657.rst  @pfmoore
The PEP number 657 has now been taken - can you update this to the next free number? Might be worth waiting until @dholth has got the CLA sorted, so we don't have to keep changing.

2021-05-08 18:19 UTC, pfmoore commented on pep-0657.rst
> +PEP: 657
PEP number needs changing here too.

2021-05-11 21:35 UTC, brettcannon commented
More importantly the CLA issue needs to be resolved before fixing the issue number is necessary in case it shifts again.

2021-05-14 12:50 UTC, pfmoore commented
I'm not going to be able to keep checking this PR - can @dholth or someone else please explicitly @-ping me when the CLA issue is resolved?

2021-05-19 12:15 UTC, pradyunsg commented
@dholth nudge. Any updates on when you might be able to sign the CLA?

2021-05-20 18:56 UTC, brettcannon approved these changes

2021-05-20 18:58 UTC, merged

2021-05-27 02:57 UTC, frostming commented on pep-0660.rst
> +Build backends may use different techniques to achive the goals of an editable
A small typo: `achieve`