PEP 659: Specializing Adaptive Interpreter
python/peps pull request #1957
Opened 2021-05-11 12:33 UTC by markshannon

2021-05-11 12:59 UTC, JelleZijlstra requested changes
Added some wording suggestions.

2021-05-11 12:59 UTC, JelleZijlstra commented on pep-0659.rst
> +Whilst Python will never attain the performance of low-level langauges like C, Fortran, or even Java,
```suggestion
Whilst Python will never attain the performance of low-level languages like C, Fortran, or even Java,
```

2021-05-11 12:59 UTC, JelleZijlstra commented on pep-0659.rst
> +Specialization at the level on individual bytecodes makes deoptimization trivial, as it cannot occur in the middle of a region.
```suggestion
Specialization at the level of individual bytecodes makes deoptimization trivial, as it cannot occur in the middle of a region.
```

2021-05-11 12:59 UTC, JelleZijlstra commented on pep-0659.rst
> +and trivial to implement, de-optimizations.
```suggestion
and trivial to implement, deoptimizations.
```

2021-05-11 12:59 UTC, JelleZijlstra commented on pep-0659.rst
> +Quickened code has number of advantages over the normal bytecode:
```suggestion
Quickened code has a number of advantages over the normal bytecode:
```

2021-05-11 12:59 UTC, JelleZijlstra commented on pep-0659.rst
> +In order that tracing can supported, and quickening performed quickly, the quickened instruction format should match the normal
```suggestion
In order that tracing can be supported, and quickening performed quickly, the quickened instruction format should match the normal
```

2021-05-11 12:59 UTC, JelleZijlstra commented on pep-0659.rst
> +Each entry will be 8 bytes (for a 64 bit machine). The data in a entry, and the number of entries needed, will vary from instruction to instruction.
```suggestion
Each entry will be 8 bytes (for a 64 bit machine). The data in an entry, and the number of entries needed, will vary from instruction to instruction.
```

2021-05-11 14:27 UTC, merged

2023-01-10 00:31 UTC, WM7586 approved these changes

2023-01-10 02:20 UTC, WM7586 requested changes
pep-0659.rst

2023-01-10 04:47 UTC, CAM-Gerlach commented
@python/organization-owners Spam x2 :point_up_2: