TBD: Persistent cache for packaging frontends
python/peps pull request #1976
Opened 2021-06-03 08:34 UTC by gaborbernat

Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>

2021-06-03 12:16 UTC, uranusjr commented on pep-9999.rst
> +Discussions-To: https://discuss.python.org/t/proposal-adding-a-persistent-cache-directory-to-pep-517-hooks/2303/57
Would it be better to start a new thread instead? This thread is already quite long and can be difficult to follow for newcomers.

2021-06-03 12:17 UTC, uranusjr commented on pep-9999.rst
> +.. _`PEP-517`: https://www.python.org/dev/peps/pep-0517/
PEPs are automatically linked, so this is not needed, and all references can simply use `` :pep:`517` ``.

2021-06-03 21:39 UTC, brettcannon commented
Please word wrap the text. See https://www.python.org/dev/peps/pep-0012/#general for guidance.

2021-06-04 18:31 UTC, brettcannon requested changes
For final merging, the PEP references should be plain text for automatic linking and the text needs to be reflowed as appropriate.

2021-06-04 18:31 UTC, brettcannon commented on pep-9999.rst
> +This document describes extensions to the build backend and frontend communication (as introduced by `PEP-517`_) to allow frontends to manage build backend
PEPs are automatically linked.
```suggestion
This document describes extensions to the build backend and frontend communication (as introduced by PEP 517) to allow frontends to manage build backend
```

2021-10-04 09:19 UTC, gaborbernat commented
I'll close this for now and reopen it later when I have more bandwidth for this :blush: thanks for the reviews.

2021-10-04 09:19 UTC, closed without merging