TBD: Editable installs
python/peps pull request #1977
Opened 2021-06-03 09:58 UTC by gaborbernat

Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>

2021-06-03 21:38 UTC, brettcannon commented
Would you mind word wrapping this? See https://www.python.org/dev/peps/pep-0012/#general for guidance.

2021-06-03 21:41 UTC, gaborbernat commented
Uh, ok doing that makes a PITA to make amendments to the PEP because you have to reindent multiple lines manually after every edit. Ideally we should do that just before merging not?

2021-06-03 22:12 UTC, brettcannon commented
If you're explicitly asking for the rest of the PEP to be reviewed before reflowing that's fine, but the reflow will need to happen before the PEP can be accepted.

2021-06-03 22:16 UTC, JelleZijlstra commented
I don't think every edit needs to trigger a complete reflow. If you need to add a few words to the middle of a paragraph later, you can just have a shorter line in the middle and leave the rest of the paragraph alone. The thing to aim for is that every line stays within the length limit.

2021-06-04 09:05 UTC, pradyunsg commented on pep-9999.rst
> +Discussions-To: https://discuss.python.org/t/draft-pep-editable-installs-for-pep-517-style-build-backends/8510
Use the topic about this specific PEP draft, rather than PEP 660's topic?

```suggestion
Discussions-To: https://discuss.python.org/t/9071
```

2021-06-04 20:09 UTC, brettcannon requested changes
LGTM overall, but I want to double-check that the `:pep:` directives actually turn into hyperlinks as I didn't think they did thanks to us not using sphinx.

2021-06-04 20:09 UTC, brettcannon commented on pep-9999.rst
> +   startup of it. This is done by creating a ``pth`` file into the target
```suggestion
   startup of the interpreter. This is done by creating a ``pth`` file into the target
```

2021-06-04 20:09 UTC, brettcannon commented on pep-9999.rst
> +   install -e <project_directory>`_ translate too. This solution is fast and
```suggestion
   install -e <project_directory>`_ translates to. This solution is fast and
```

2021-06-07 23:30 UTC, brettcannon requested changes
LGTM! Can you add me as the sponsor, take the next PEP number (662), and add me to `.github/CODEOWNERS`? I will then approve and merge this.

2021-06-07 23:43 UTC, gaborbernat commented
Sure, I'll ask another day or two to do some clarifications that came up on the discussion topic 🙏 thanks!

2021-06-11 11:06 UTC, gaborbernat commented
> LGTM! Can you add me as the sponsor, take the next PEP number (662), and add me to `.github/CODEOWNERS`? I will then approve and merge this.

All done now 👍 thanks!

2021-06-11 11:31 UTC, pradyunsg commented
You'd wanna retitle the PR. :)

2021-06-11 12:26 UTC, layday commented on pep-0662.rst
> +The schema paths map from project source absolute paths to target directory
Nit: should be "scheme", not "schema".

2021-06-11 19:33 UTC, brettcannon approved these changes

2021-06-11 19:34 UTC, merged